### PR TITLE
Implemented key client library

### PR DESCRIPTION
**Pull request by rayrobdod**
This is the half of the networking that goes on the arduino.

I don't think that missing the esp8266 half of the library should block integration efforts between this and the motor or distance libraries. The hardware can stub it easily enough.

I, without removing any wires, added wires such that the arduino is configured to run the "indicateDone.ino" sketch, and the oscilloscope is configured to observe it. You probably want to see that yourself before approving this.

### CODE REVIEW

**Comment by dxa4481** [comment]
Can you explain what all the CuTest stuff is? This example doesn't have all that stuff https://github.com/mity/cutest

Is this the library itself you committed? I think it's generally best practice to not commit that, and to just include either a makefile or install instructions.

Also, we created test folders inside the libraries/ folder, so each library gets its own tests folder and own tests.

**Comment by rayrobdod** [comment]
Joy. https://github.com/mity/cutest and http://cutest.sourceforge.net/ have nothing to do with each other despite having the same name.

I may have said this already, but C has no dependency management system, and even if there were, there are no C libraries using it. Seeing as you put a link to imgur in the readme, whatever I say will fall on deaf ears, but the point of version control is that anyone can checkout any commit at any time and produce the exact same build as the original committer. Without either a standard dependency management system or putting the dependency in the repository, I do not see how that goal can be achieved.

**Comment by dxa4481** [comment]
As I mentioned before, can this be achieved with a makefile that simply pulls down the version of cutest we're using? 

I believe we can move the images from imgur into the repository if you'd prefer it that way, I just don't like cluttering up the repository with large binary files that need to get pulled down every time someone clones the code.

**Comment by rayrobdod** [comment]
So, what, cURL `http://downloads.sourceforge.net/project/cutest/cutest/1.5/cutest-1.5.zip?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fcutest%2Ffiles%2Fcutest%2F1.5%2F&ts=1442257711&use_mirror=skylineservers`, and hope that that url doesn't change without any guarantee form SF, and that cURL can handle whatever redirects lead to the download being from the domain `iweb.dl.sourceforge.net`? Or maybe host a mirror myself?

I'd rather no images at all, especially not photos. Those seem more post-project-website material than readme material.

**Comment by dxa4481** [comment]
Yes, the curl command is exactly what I had in mind. Our project has certain dependencies. It depends on the Arduino IDE, it depends on an operating system to run the Arduino IDE, it depends on having an Arduino. 
We don't package the Arduino IDE into the repository, right? It should be mentioned as a requirement in the README in my opinion. In my opinion cuTest should function the same way, and possibly for convenience a makefile that automatically pulls cuTest down. That's the way I've seen these types of dependencies handled in the past. The idea is to keep this repository as clean as possible.

Regarding images in the README, lots of projects do this, such as this one https://github.com/black-screen/black-screen the github README is written in markdown and intended for viewing on github. _Much like these comments_, they are meant to contain graphical formatting they are meant to be rendered and viewied on github

**Comment by dxa4481** [comment]
Ultimately we can also use Travis for testing https://travis-ci.org/
I've never used it before but it natively integrates with github and will run our CuTests for us for every pull request.

**Comment by dxa4481** [comment]
I have some good news. I found a C package manager that actually has CuTest https://github.com/clibs/clib/wiki/Packages

Let me know what you think.

**Comment by rayrobdod** [comment]
The decision regarding wireless appeared to be "The projected risk of device interference did not actually occur, therefore this risk-mitigation technique is completely unnecessary".

**Pull request closed without merging**
